### ISSUE TITLE
Chapter 4.2

### ISSUE THREAD

**Issue by bkhobart** [noamross/gams-in-r-course#26]
Hi Noam,

I've been running through the course (which is beautiful, by the way) with no difficulties until now. When trying to run `csale <- readRDS("csale.rds")` in Chapter 4.2, I receive the error pasted below. R is up-to-date and the "Information" package is loaded (just in case).

Cheers, Brendan

Error message:
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'csale.rds', probable reason 'No such file or directory'

**Comment by SailStripes** [comment]
Hi. don't know whether you still need an answer but I managed to fix it! Basically go onto the repository on this site and manually download the csale.rds file (https://github.com/noamross/gams-in-r-course/blob/master/csale.rds). save this somewhere, e.g. C:/Data/Rfiles. Then in R you need to set the 'working directory' with: setwd("C:/Data/Rfiles)... Then just rerun the code mentioned in the exercise: readRDS("csale.rds")... worked for me atleast.

**Comment by bkhobart** [comment]
Thanks for the answer and solution, very much appreciated! Been a while since I revisited the course, but it's a great resource.

Cheers,
Brendan
