### ISSUE TITLE
Remove "Let's Practice" slides

### ISSUE THREAD

**Issue by noamross** [noamross/gams-in-r-course#4]
Most slide decks end with a "Let's Practice" or similar sllide but in the current format this isn't really necessary - it's a holdover from the old platform.  It would make sense to delete these from the `slides` markdown files.

**Comment by xdesro** [comment]
Hey @noamross -- is this as simple as deleting the text in content files, or did you have more specific ideas about something to replace the "Let's Practice" slides? I'm about ready and would love to PR this if it's just editing those Markdown files in the `slides/` dir, I just wanted to make sure you didn't have more in mind!
